### ISSUE TITLE
Doesn't Actually Send Data

### ISSUE THREAD

**Issue by seanadkinson** [vvo/analytics.js-loader#6]
I think this library doesn't actually do the right thing.  Real issue being the goofy way Segment has done their JS.  When the analytics script is loaded, it doesn't actually fix the initial `window.analytics`, it just replaces it, and the fact that this module exports a reference to the initial object, means that after the script is loaded, events aren't actually sent to Segment and tracked.

I could be wrong, but that is what I was observing.

Here is the module I created to fix this issue:

```
import loadAnalytics from 'analytics.js-loader';

/*
 * The analytics.js-loader module returns the "initial" analytics
 * object, which is basically just a queue to hold events until the
 * "real" one is loaded with a global script.  Problem is, the "real"
 * one simply replaces `window.analytics`, and doesn't change over
 * this initial "queue" object, meaning that nothing gets registered
 * after the "real" one is loaded - things just keep adding to the queue.
 * This is why we save off `initialAnalytics`, and then always run
 * methods through `window.analytics`, which might be the queue, and
 * might be the real one.
 */
const initialAnalytics = loadAnalytics({
    writeKey: 'KEY',
    skipPageCall: true
});
window.analytics = initialAnalytics;

const analytics = {};
_.each(initialAnalytics.methods, method => {
    analytics[method] = function() {
        return window.analytics[method].apply(window.analytics, arguments);
    };
});

export default analytics;
```

**Comment by vvo** [comment]
I am no more using this project, cc @contra I believe you are using it and it works right? Can you have a quick look at what @seanadkinson said? thx

**Comment by yocontra** [comment]
Here is my code, using my fork (https://github.com/contra/analytics.js-loader):

``` coffee
loadAnalytics = require 'analytics.js-loader'

key = 'your segment key'
analytics = loadAnalytics key

if analytics?
  console.log '[Analytics] Loaded'
  module.exports = ->
    loadAnalytics key
else
  console.log '[Analytics] Failed to load'
  module.exports = null
```

**Comment by vvo** [comment]
@contra Can you do a PR if you have more fixes? Actually you are now owner of both the github and npm repo so you can do anything you want here:)

**Comment by mmahalwy** [comment]
@seanadkinson same problem here - its not actually working...

**Comment by seanadkinson** [comment]
@mmahalwy Try my code above... it has been working well for me.

**Comment by vvo** [comment]
Are you guys saying the currently published module is not working at all? Would you mind submitting a patch, @seanadkinson ?

**Comment by ghost** [comment]
I encountered the same issue, it does appear the currently published module doesn't work for the reasons that @seanadkinson outlined. His module works perfectly for me. Would be happy to see this integrated into the library.

**Comment by ghost** [comment]
Thanks for merging @vvo!

**Comment by ghost** [comment]
@vvo Oops, looks like I didn't tag the commit though. Mind adding the `2.1.2` tag so we can install this using `npm` now?

**Comment by vvo** [comment]
I think I published it

**Comment by ghost** [comment]
Ah, so you did, just didn't see it in GitHub tags. Thanks!

**Comment by vvo** [comment]
actually there's no real need to push tags when publishing on npm, this is just a convenience/consistency for users but no need

**Comment by vvo** [comment]
npm doesnt care about the github tags
